# -*- coding: utf-8 -*-
"""Car_Prices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3uIdwbJXB0d-LSnfwpyTJUuk0XeR7Po

**Import Libraries**
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

from sklearn.preprocessing import StandardScaler

"""**Load the dataset and add column names**"""

url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv"

columns = [
    "symboling", "normalized-losses", "make", "fuel-type", "aspiration",
    "num-of-doors", "body-style", "drive-wheels", "engine-location",
    "wheel-base", "length", "width", "height", "curb-weight",
    "engine-type", "num-of-cylinders", "engine-size", "fuel-system",
    "bore", "stroke", "compression-ratio", "horsepower", "peak-rpm",
    "city-mpg", "highway-mpg", "price"
]

df = pd.read_csv(url, names=columns)

df.head()

print("Dataset shape:", df.shape)

df.head(10)

"""**Replace missing values**"""

df.replace("?", np.nan, inplace=True)

df.isnull().sum()

"""**Convert important columns to numeric**"""

numeric_columns = [
    "normalized-losses", "bore", "stroke", "horsepower",
    "peak-rpm", "price"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

"""**Fill missing values**"""

df["normalized-losses"] = df["normalized-losses"].fillna(df["normalized-losses"].mean())
df["bore"] = df["bore"].fillna(df["bore"].mean())
df["stroke"] = df["stroke"].fillna(df["stroke"].mean())
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mean())
df["peak-rpm"] = df["peak-rpm"].fillna(df["peak-rpm"].mean())

df["num-of-doors"] = df["num-of-doors"].fillna(df["num-of-doors"].mode()[0])

"""**Descriptive statisctics**"""

df.describe()

"""**Mean, Mode, Standard Deviation**"""

print("Mean values:")
print(df[["price", "horsepower", "engine-size", "city-mpg"]].mean())

print("\nMedian values:")
print(df[["price", "horsepower", "engine-size", "city-mpg"]].median())

print("\nStandard deviation:")
print(df[["price", "horsepower", "engine-size", "city-mpg"]].std())

df.dtypes

categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    print(col)
    print(df[col].unique())
    print()

"""**Histogram of Price**"""

plt.figure(figsize=(8, 5))
plt.hist(df["price"], bins=20)
plt.title("Distribution of Car Prices")
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.show()

"""**Histogram of Horsepower**"""

plt.figure(figsize=(8, 5))
plt.hist(df["horsepower"], bins=20)
plt.title("Distribution of Horsepower")
plt.xlabel("Horsepower")
plt.ylabel("Frequency")
plt.show()

"""**Boxplot price vs body-style**"""

plt.figure(figsize=(9, 5))
sns.boxplot(x="body-style", y="price", data=df)
plt.title("Price by Body Style")
plt.xlabel("Body Style")
plt.ylabel("Price")
plt.show()

"""**Correlation Heatmap**"""

plt.figure(figsize=(12, 8))
numeric_df = df.select_dtypes(include=["int64", "float64"])
sns.heatmap(numeric_df.corr(), annot=False, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

"""**Create new feature city-L/100km**"""

df["city-L/100km"] = 235 / df["city-mpg"]

df[["city-mpg", "city-L/100km"]].head()

"""**Horsepower binning**"""

bins = np.linspace(df["horsepower"].min(), df["horsepower"].max(), 4)
labels = ["Low", "Medium", "High"]

df["horsepower-binned"] = pd.cut(df["horsepower"], bins=bins, labels=labels, include_lowest=True)

df[["horsepower", "horsepower-binned"]].head()

df["horsepower-binned"].value_counts()

"""**Normalize one feature**"""

df["length-normalized"] = df["length"] / df["length"].max()

df[["length", "length-normalized"]].head()

"""**Features for Regression**"""

features = ["horsepower", "engine-size", "curb-weight", "width", "city-L/100km"]

X = df[features]
y = df["price"]

"""**80/20 split**"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

lr_r2 = r2_score(y_test, y_pred_lr)
lr_mae = mean_absolute_error(y_test, y_pred_lr)
lr_mse = mean_squared_error(y_test, y_pred_lr)

print("Linear Regression Results - 80/20 Split")
print("R2 Score:", lr_r2)
print("MAE:", lr_mae)
print("MSE:", lr_mse)

"""**Random Forest Regressor**"""

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

rf_r2 = r2_score(y_test, y_pred_rf)
rf_mae = mean_absolute_error(y_test, y_pred_rf)
rf_mse = mean_squared_error(y_test, y_pred_rf)

print("Random Forest Results - 80/20 Split")
print("R2 Score:", rf_r2)
print("MAE:", rf_mae)
print("MSE:", rf_mse)

"""**Compare 80/20 and 70/30 split**"""

X_train_70, X_test_70, y_train_70, y_test_70 = train_test_split(
    X, y, test_size=0.30, random_state=42
)

lr_model_70 = LinearRegression()
lr_model_70.fit(X_train_70, y_train_70)

y_pred_lr_70 = lr_model_70.predict(X_test_70)

print("Linear Regression Results - 70/30 Split")
print("R2 Score:", r2_score(y_test_70, y_pred_lr_70))
print("MAE:", mean_absolute_error(y_test_70, y_pred_lr_70))
print("MSE:", mean_squared_error(y_test_70, y_pred_lr_70))

rf_model_70 = RandomForestRegressor(random_state=42)
rf_model_70.fit(X_train_70, y_train_70)

y_pred_rf_70 = rf_model_70.predict(X_test_70)

print("Random Forest Results - 70/30 Split")
print("R2 Score:", r2_score(y_test_70, y_pred_rf_70))
print("MAE:", mean_absolute_error(y_test_70, y_pred_rf_70))
print("MSE:", mean_squared_error(y_test_70, y_pred_rf_70))

"""**Actual Vs Predicted graph**"""

plt.figure(figsize=(8, 5))
plt.scatter(y_test, y_pred_rf)
plt.title("Actual vs Predicted Car Prices")
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.show()

"""**price categories for classification**"""

df["price-category"] = pd.qcut(
    df["price"],
    3,
    labels=["Low", "Medium", "High"]
)

df[["price", "price-category"]].head()

"""**Logistic Regression classification**"""

X_class = df[features]
y_class = df["price-category"]

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X_class, y_class, test_size=0.20, random_state=42
)

scaler = StandardScaler()

X_train_c_scaled = scaler.fit_transform(X_train_c)
X_test_c_scaled = scaler.transform(X_test_c)

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_c_scaled, y_train_c)

y_pred_class = log_model.predict(X_test_c_scaled)

accuracy = accuracy_score(y_test_c, y_pred_class)

print("Classification Accuracy:", accuracy)

"""**Confusion Matrix**"""

cm = confusion_matrix(y_test_c, y_pred_class, labels=["Low", "Medium", "High"])

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Low", "Medium", "High"]
)

disp.plot()
plt.title("Confusion Matrix for Price Category Classification")
plt.show()

"""**Final Model Comparison**"""

results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest"],
    "R2 Score": [lr_r2, rf_r2],
    "MAE": [lr_mae, rf_mae],
    "MSE": [lr_mse, rf_mse]
})

results

"""**Clean Dataset Saving**"""

df.to_csv("cleaned_car_price_data.csv", index=False)